### ISSUE TITLE
Shutdown doesn't handle `Async::NotReady`

### ISSUE THREAD

**Issue by griff** [tokio-rs/tokio-io#100]
`AsyncWrite::shutdown` returns a `Poll` but the `Shutdown` struct returned from `shutdown` calls `try_nb!` and so ignores `Async::NotReady` returned from `AsyncWrite::shutdown`.

**Comment by alexcrichton** [comment]
Thanks for the report! I think I'm a little lost in the types, could you point out in the code where this happens?

**Comment by griff** [comment]
Sorry for the confusing explanation. The problem is here: https://github.com/tokio-rs/tokio-io/blob/53790e484c46089ae2b782644f1fe0c7ed815518/src/shutdown.rs#L41

I think it should should use `try_ready!` instead of `try_nb!` there.

**Comment by griff** [comment]
Or it should at least use both:
`
try_ready!(try_nb!(self.a.as_mut().unwrap().shutdown()));
`

**Comment by alexcrichton** [comment]
Ah yes indeed I believe that should be using `try_ready!` instead of `try_nb!`, nice catch! Want to send a PR?

**Comment by carllerche** [comment]
The tokio-io crate has been moved into the [tokio](https://github.com/tokio-rs/tokio) git repo.

I created a new issue over there. See link above.
