### ISSUE TITLE
Location of AsyncRead/AsyncWrite traits

### ISSUE THREAD

**Issue by alexcrichton** [tokio-rs/tokio-io#19]
Right now they're only at the root but often I'd like to do:

```rust
use tokio_io::io::{some_combinator, AsyncRead};
```

Maybe we can reexport?

**Comment by carllerche** [comment]
I don't have an opinion.

**Comment by carllerche** [comment]
I think this will be better handled by re-exporting them both in the tokio crate: `use tokio::io::{AsyncRead, some_combinator};`

If you agree, we can open an issue on the tokio crate to track re-exports & reference this.

**Comment by carllerche** [comment]
The tokio-io crate has been moved into the [tokio](https://github.com/tokio-rs/tokio) git repo.
