### ISSUE TITLE
write_buf/read_buf not object safe

### ISSUE THREAD

**Issue by alexcrichton** [tokio-rs/tokio-io#22]
In general this may not be too bad but it means that `Box<AsyncRead>` won't actually use any optimizations implemented below

**Comment by carllerche** [comment]
Is there anything that can be done about it?

**Comment by carllerche** [comment]
One option would be to provide `read_vec` and `write_vec` on `AsyncRead` and `AsyncWrite`. The default impl would be to pass that to `read_buf` and `write_buf` (by wrapping the provided iovec array in a buf implementation).

Then there could be an impl of `read_buf` on `Box<AsyncRead>` that calls read_vec under the hood, which then gets back to read_buf on the other side...

A little convoluted.

**Comment by alexcrichton** [comment]
Oh one option is to remove the generics and use trait objects as well. That is:

```rust
trait AsyncRead {
    fn read_buf(&mut self, buf: &mut BufMut) -> Poll<usize, std_io::Error> {
        // ... 
    }
}
```

**Comment by carllerche** [comment]
I'd prefer to avoid trait objects as the argument. I think using AsyncRead as a trait object will be less likely.

**Comment by aturon** [comment]
We can always layer such a method over the current `read_buf`, giving it a default impl that just invokes `read_buf` with the trait object.

**Comment by carllerche** [comment]
@aturon could you provide an example of what you mean? I'm not following.

**Comment by alexcrichton** [comment]
I believe:

```rust
fn read_buf1<T: BufMut>(&mut self, buf: &mut T) -> io::Result<usize>
    where Self: Sized
{
    self.read_buf2(buf)
}

fn read_buf2(&mut self, buf: &mut BufMut) -> io::Result<usize> {
    // current implementation of `AsyncRead::read_buf` on master
}
```

**Comment by carllerche** [comment]
Is there an example of this in std? What are the pros / cons?

**Comment by alexcrichton** [comment]
AFAIK no, the pro is that it supports everything but the con is complexity, unfortunately.

**Comment by carllerche** [comment]
Has this ended up being an issue in practice?

**Comment by carllerche** [comment]
Is this still an issue or should it be closed?

**Comment by alexcrichton** [comment]
Ok let's close.
