### ISSUE TITLE
Consider adding `'static` bounds to `Encoder` and `Decoder` Item types

### ISSUE THREAD

**Issue by alexcrichton** [tokio-rs/tokio-io#26]
Moved from https://github.com/tokio-rs/tokio-core/issues/83

**Comment by carllerche** [comment]
This has not been an issue for me. Is this still an issue in practice?

**Comment by carllerche** [comment]
The tokio-io crate has been moved into the [tokio](https://github.com/tokio-rs/tokio) git repo.

This issue has been inactive, so I am not going to open a new one in the tokio repo. However, if anyone wishes to continue this discussion, please feel free to open a new issue over there.
