### ISSUE TITLE
BytesMut lacks a direct implementation of std::io::Write

### ISSUE THREAD

**Issue by NeoLegends** [tokio-rs/tokio-io#28]
I'm currently using the `codec` module to implement a framed tansport.

Before the refactoring, the `encode`-method of the old `Codec` trait received a `Vec<u8>` as parameter to serialize the message into. `Vec<u8>` directly implements `std::io::Write` which makes it very easy to put any kind of data into it, since most implementations have some way of writing into an instance of `Write`.

Now the `Vec<u8>` has been replaced by `BytesMut`, which lacks a direct implementation of that trait. `Write`-compatibility is only archievable through `into_writer`, which consumes the `BytesMut`. Consuming is not possible, though, because the method only receives the `BytesMut` by `&mut`.

Is this desired behavior?

**Comment by carllerche** [comment]
into_writer should work because BufMut is also implemented on &mut BytesMut. So you are passing ownership of the ref, not the value. 

That being said, unless there is a coherence problem (which I don't think there is) I don't see why BytesMut couldn't impl Writer directly.

**Comment by carllerche** [comment]
Could you open an issue in the bytes repo and reference this one?

**Comment by NeoLegends** [comment]
> into_writer should work because BufMut is also implemented on &mut BytesMut.

Right now it doesn't, unfortunately. 

> Could you open an issue in the bytes repo and reference this one?

Sure! Thanks for the quick support!

**Comment by Ralith** [comment]
Can't you use [`BufMut::writer`](https://docs.rs/bytes/0.4/bytes/trait.BufMut.html#method.writer)? This is working fine for me, for the reasons @carllerche gave. I don't even see an `into_writer` method.

**Comment by NeoLegends** [comment]
Oh man, sorry. You guys are right. I was mislead.
