### ISSUE TITLE
Support for async seeking

### ISSUE THREAD

**Issue by est31** [tokio-rs/tokio-io#31]
It would be cool to have async seeking support, additionally to async writing and async reading. I would need it for a tokio backend for a planned version of my ogg crate that supports seeking and has better async support. Otherwise I'd have to continue to rolly my own, which I wouldn't want.

**Comment by carllerche** [comment]
Hi, could you elaborate a bit more, I'm not that I understand the problem or the proposed solution.

What is "async seeking support" and why is it needed?

**Comment by est31** [comment]
There are traits `tokio_io::AsyncRead` and `tokio_io::AsyncWrite`, corresponding to the `std::io::Read` and `std::io::Write` traits. There is none for `std::io::Seek`.

**Comment by carllerche** [comment]
Right, but one big reason for adding `AsyncRead` / `AsyncWrite` was to add additional fns. Unless you *only* want to take a `T: Seek`, there is no need to add an `AsyncSeek` trait, you can just take `AsyncRead + Seek`.

**Comment by est31** [comment]
Thanks for the input. I'm still a beginner regarding the tokio library. I'll do some consideration, and if I still see demand for that trait I'll reopen.

**Comment by carllerche** [comment]
No worries, hopefully it works for you.
