### ISSUE TITLE
Can't make trait objects out of AsyncWrite

### ISSUE THREAD

**Issue by sid0** [tokio-rs/tokio-io#32]
Because method `write_buf` has generic type parameters.

For my use case where using a trait object is essential, I'm not sure how to get around this. :(

**Comment by sid0** [comment]
If `write_buf` is a purely auxiliary method (from the docs it's not clear if `AsyncWrite` wrappers should implement it), would you consider moving it out of the trait?

**Comment by alexcrichton** [comment]
Oops definitely an accidental omission!

**Comment by sid0** [comment]
Thanks!
