### ISSUE TITLE
AsyncWrite wrappers that consume self can fail because of WouldBlock

### ISSUE THREAD

**Issue by sid0** [tokio-rs/tokio-io#35]
See https://github.com/gyscos/zstd-rs/issues/22 as an example. There's a method called `finish()` which consumes `self` but could potentially fail because of `WouldBlock`.

This can lead to writers being stuck in an unrecoverable state even though all they needed to do was retry on next `poll()`.

Is there any way to handle this short of adding a non-consuming version of any methods that could consume self yet cause writes?

**Comment by sid0** [comment]
I guess `shutdown()` is meant to solve this sort of use case? But it would mean that we'd have to convince any third-party crates to (optionally?) depend on `tokio-io` and add shutdown methods of their own.

**Comment by alexcrichton** [comment]
Ah yes the intention here is for `AsyncWrite::shutdown` to implement this logic. Presumably there's an `impl AsyncWrite` somewhere though for this type, right? Where's that located?

**Comment by sid0** [comment]
I implemented it locally in my crate. Here's what the source code looks like: https://gist.github.com/sid0/2afeda9cb29e7250acce9badcc9727eb

**Comment by alexcrichton** [comment]
If you add:

```rust
try_nb!(self.flush())
```

to the `shutdown` function, would that work?

**Comment by sid0** [comment]
No, because `finish()` does a write at the end that cannot be done any other way.

**Comment by sid0** [comment]
For reference: https://docs.rs/zstd/0.4.6/src/zstd/stream/encoder.rs.html#188

The `ZSTD_endStream` writes out an end-of-stream marker.

**Comment by alexcrichton** [comment]
Aha I see now, good point!

I think that this is a case where the upstream crate needs to have support in *some* form, although not necessarily with tokio-io itself. Presumably `ZSTD_endStream` is properly reentrant, right? In the sense that if it returns "would block" you can come back later and try again?

**Comment by sid0** [comment]
That's actually a good point. There are two spots where `finish()` can fail.

1. `ZSTD_endStream` -- this shouldn't happen in normal use.
2. `self.writer.write_all` -- this is what would likely fail with `WouldBlock`.

I don't actually know if the underlying C function `ZSTD_endStream` is re-entrant. I suspect not. But that can be handled in the wrapper by adding some state about whether the end-of-stream marker has been written.

**Comment by alexcrichton** [comment]
Oh right sorry good point, the issue here looks to be with `self.writer.write_all`, not with `ZSTD_endStream`. In that sense yeah I think that there needs to be some kind of `try_finish` which doesn't return the inner writer, or does something like:

```rust
fn finish(self) -> Result<W, (Self, io::Error)>
```

**Comment by sid0** [comment]
BTW do your bzip2 and flate2 crates have the same problem?

**Comment by alexcrichton** [comment]
Ayup, I believe so!

**Comment by alexcrichton** [comment]
I've [opened an issue for flate2](https://github.com/alexcrichton/flate2-rs/issues/91)

**Comment by sid0** [comment]
OK. This would be worth documenting somewhere in a general "notes" section so that people don't have to learn this the hard way :)

**Comment by carllerche** [comment]
@sid0 We'd appreciate a PR offering documentation :)

**Comment by sid0** [comment]
Still working on internal legal approval, unfortunately :( will hopefully have it in a couple of weeks

**Comment by alexcrichton** [comment]
@sid0 if you don't get around to it first I'll try to update the docs in this regard and I'll also try to tackle the flate2 issues soon.

**Comment by alexcrichton** [comment]
Ok I'm going to close this in favor of the flate2 issue, as I think that this is solved now with updated docs? Otherwise pending work is in the various external crates.

Let me know if this is in error though!
