### ISSUE TITLE
AsyncWrite::shutdown semantics are a little unclear

### ISSUE THREAD

**Issue by sid0** [tokio-rs/tokio-io#36]
I was having a look at the [docs for `shutdown`](https://docs.rs/tokio-io/0.1.1/tokio_io/trait.AsyncWrite.html#tymethod.shutdown) and they're a bit unclear to me.

> This shutdown method is required by implementors of the AsyncWrite trait. Wrappers typically just want to proxy this call through to the wrapped type, and base types will typically implement shutdown logic here or just return Ok(().into()).

Is this always the case? In https://github.com/tokio-rs/tokio-io/issues/35 we found a case where we might want to call `shutdown` to write out the zstd end-of-stream marker but not to actually shutdown the underlying `AsyncWrite` -- maybe you'd want to write more data to it afterwards? Is that even a legit use case for `shutdown`?

> Invocation of a shutdown implies invocation of flush. Once this method returns Ready it implies that a flush successfully happened before the shutdown happened.

What does that mean? Do I as an implementer of `shutdown` have to call `self.flush` inside it unconditionally? If I'm a wrapper over another `AsyncWrite`, do I only have to call `self.flush` if I have some internal buffering?

**Comment by alexcrichton** [comment]
Ah yeah so to clarify, `shutdown` is definitely allowed to write more data. (that's it's use case!)

Otherwise a `shutdown` implies a `flush` in the sense that you're not required to flush a connection when you start the shutdown process, that should happen automatically. Implementors of shutdown will then typically start by calling flush, yes.

Does that help?

(I can update the docs to this effect if so)

**Comment by sid0** [comment]
> Ah yeah so to clarify, shutdown is definitely allowed to write more data.

OK, but does `shutdown` on a wrapper also transitively imply `shutdown` on the thing it wraps? That bit isn't really clear.

> you're not required to flush a connection when you start the shutdown process

Got it. The "you" is a little confusing. Maybe call it "caller" or "consumer".

**Comment by alexcrichton** [comment]
Ok cool, I'll push a clarification.

Also, yeah, a `shutdown` on a wrapper implies a transitive flush and then a transitive shutdown
