### ISSUE TITLE
Document that std write_all is incompatible with non-blocking IO

### ISSUE THREAD

**Issue by sid0** [tokio-rs/tokio-io#38]
`std::io::Write::write_all` is incompatible with non-blocking IO, because it can do partial writes then fail, and the caller cannot find out how many bytes were actually written. This also applies to libraries that might call `write_all` internally -- they cannot be used with non-blocking IO.

It would be good to document this restriction somewhere. It might also be worth making `AsyncWrite` panic on `write_all`?

I've filed https://github.com/alexcrichton/flate2-rs/issues/92 and https://github.com/alexcrichton/bzip2-rs/issues/17 for known users in a couple of crates.

**Comment by carllerche** [comment]
This seems like an unfortunate flaw with the stdlib traits and should probably be documented.

**Comment by carllerche** [comment]
The tokio-io crate has been moved into the [tokio](https://github.com/tokio-rs/tokio) git repo.

I created a new issue over there. See link above.
