### ISSUE TITLE
Panic when codec produces frames larger than 8kb 

### ISSUE THREAD

**Issue by NikVolf** [tokio-rs/tokio-io#42]
I believe this code will panic once arbitrary `Codec::encode` implementation provides frame longer than 8kb (`INITIAL_CAPACITY`):

https://github.com/tokio-rs/tokio-io/blob/master/src/framed_write.rs#L190

Can it be configured? Or any workaround if service responses can be longer?

**Comment by alexcrichton** [comment]
Oh the `BufMut` is a growable vector of bytes, but many functions don't grow by default. You can see more here: https://docs.rs/bytes/0.4.3/bytes/struct.BytesMut.html#growth

**Comment by NikVolf** [comment]
Cool, thanx! 
btw, does it got shrink anywhere (imagine responses of length 1, 1, 1, 655360, 1, 1, ... )?

**Comment by carllerche** [comment]
This shrinks it: https://github.com/tokio-rs/tokio-io/blob/master/src/framed_write.rs#L210
