### ISSUE TITLE
length_delimited::Framed length adjustment

### ISSUE THREAD

**Issue by polachok** [tokio-rs/tokio-io#47]
It's a bit weird that it's possible to adjust length while decoding and not possible when encoding.
I'm working with a protocol which looks like this:

```
|~~~   Packet 1   ~~~|~~~   Packet 2   ~~~|~~~  Packet 3    ~~~|~~~

+-------+------------+-------+------------+-------+------------+...
| n=U32 | (n-4) * U8 | n=U32 | (n-4) * U8 | n=U32 | (n-4) * U8 |
+-------+------------+-------+------------+-------+------------+...

|~ Len ~|~   Data   ~|~ Len ~|~   Data   ~|~ Len ~|~   Data   ~|~
```

It doesn't seem possible to encode a correct packet with current state of things, is it?

**Comment by carllerche** [comment]
The encoding half was always meant to be simpler than decoding... however, this should be possible to support fairly easily I think. Are you interested in trying a PR?
