### ISSUE TITLE
Explicitly forward read_buf / write_buf impls in forwarding AsyncRead / AsyncWrite impls

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio-io#55]
The default implementation of read_buf / write_buf is not as good as it can be. Forwarding implementations should explicitly forward these functions too.

**Comment by alexcrichton** [comment]
You mean the impls for `&mut` and `Box`, right? If that's the case then I don't think we can because of https://github.com/tokio-rs/tokio-io/issues/22 :(

**Comment by carllerche** [comment]
No, just for the various structs like this: https://github.com/tokio-rs/tokio-io/blob/master/src/framed_write.rs#L260

**Comment by alexcrichton** [comment]
Ah indeed, makes sense!

**Comment by carllerche** [comment]
The tokio-io crate has been moved into the [tokio](https://github.com/tokio-rs/tokio) git repo.

I created a new issue over there. See link above.
