### ISSUE TITLE
Do no depend on Bytes property of preserving initial capacity

### ISSUE THREAD

**Issue by stepancheg** [tokio-rs/tokio-io#58]
Currently `Decoder` implementations depend on the fact that `Bytes` have two capacity fields: current capacity and initial capacity.

See discussion there: https://github.com/carllerche/bytes/issues/122#issuecomment-303210645

I think that part of `Bytes` is overengineered, and if initial capacity needs to be preserved, this property should be solved by tokio-io. (For example, by introducing `Bytes` wrapper which can preserve initial capacity).

**Comment by carllerche** [comment]
I believe that the answer is "won't fix". Bytes has been updated to support both the initial capacity feature as well as truncating the front: https://github.com/carllerche/bytes/pull/166.
