### ISSUE TITLE
Add AsyncBufRead

### ISSUE THREAD

**Issue by ishitatsuyuki** [tokio-rs/tokio-io#61]
`std::io::BufRead` being a trait allows zero-copy reading on already on-memory buffers. I propose here to add the similar thing in tokio-io. Adapters should also be added, either separated, or specialized (I haven't think into the detail).

One usecase of the async version is that adding additional transform on half-decoded byte buffers. In hyper, the response body is decoded into chunk, then we're going to apply gzip decoding on it (planned to be implemented in reqwest).

This should benefit tokio-tls as well.

**Comment by alexcrichton** [comment]
I've been using `AsyncRead + std::io::BufRead` for this, but what would you think `AsyncBufRead` would do differently?

**Comment by ishitatsuyuki** [comment]
Well, I still haven't found a usecase, but if there's something missing, it's the way to wait for `fill_buf`.

**Comment by alexcrichton** [comment]
Ok, in that case I believe this is solved with `AsyncRead + BufRead`. Waiting for `fill_buf` to succeed is the same as waiting for `read` to succeed.
