### ISSUE TITLE
Question: How to combine different layers of a protocol?

### ISSUE THREAD

**Issue by flosse** [tokio-rs/tokio-io#67]
I hope this is the right place to ask?
I wonder where to place different kinds of layers of a protocol and where to process **statefull** operations like adding headers with transaction IDs or checking checksums.
Let's say there are two layers: the transport layer and the high level protocol. The Frames are nested like this:

- transport A: `[HEADER_A][PDU][CHECKSUM_A]`
- transport B: `[HEADER_B][PDU]`
- transport C: `[PDU]`
- `PDU` protocol A: `[PDU_HEADER,DATA]`
- `PDU` protocol B: `[ID,META_DATA,DATA]`

How would you structure the implementation? What kind of work should be done by a codec and what should be done in higher level instances like a [ClientProto](https://docs.rs/tokio-proto/0.1.1/tokio_proto/pipeline/trait.ClientProto.html)? And how to create "nested codecs", where e.g. `PduCodecA` is used by a `TransportBCodec`?

**Comment by carllerche** [comment]
I would probably implement wrappers around the transport to handle each stage of the protocol. Kind of like here: https://github.com/tokio-rs/tokio-line/blob/master/simple/examples/ping_pong.rs#L41

**Comment by carllerche** [comment]
Hopefully this addressed the question. Cheers.
