### ISSUE TITLE
add `read_at_least` function?

### ISSUE THREAD

**Issue by cssivision** [tokio-rs/tokio-io#68]
`read_at_least` is similar to `read_exact` but read at least min bytes.  reads from reader into buf until it has read at least min bytes. It returns the number of bytes copied success , when n >= min.

**Comment by alexcrichton** [comment]
Currently the functions here match the standard library's `Read` trait, but this doesn't exist on the `Read` trait?

**Comment by cssivision** [comment]
yes, it's a helper function. this function is convenient in some situation.

**Comment by alexcrichton** [comment]
My question would basically be why it's justified to go into `tokio-io` when it was decided to *not* place it into the standard library. IIRC there was a lot of discussion about this on https://github.com/rust-lang/rfcs/pull/980

**Comment by cssivision** [comment]
thanks @alexcrichton, it spent me some time reading the whole discussion which inspired me a lot.

**Comment by carllerche** [comment]
It seems like the take away is "do nothing". As such, I will close this issue. Please let me know if this is not correct.
