### ISSUE TITLE
Does it make sense that tokio::codec::Decoder's decode method takes a BytesMut?

### ISSUE THREAD

**Issue by megmacattack** [tokio-rs/tokio-io#72]
While trying to use prost with tokio's framed codec mechanism, I found I couldn't use its decode method because it expects an IntoBuf, which BytesMut isn't (I created an issue on prost about this: https://github.com/danburkert/prost/issues/33).

But it seems to me that it doesn't make a lot of sense that decode is being given a BytesMut to begin with. A decoder probably shouldn't be modifying the underlying bytes of the buffer. Wouldn't passing in Bytes or an IntoBuf make more sense here?

**Comment by alexcrichton** [comment]
This is basically providing a static guarantee that once the bytes have been extracted you're allowed to mutate and change them as necessary. It's true that you probably don't want to modify what's already there, but I don't think we'd want to change to `Bytes` as that'd be hindering some possible applications.

**Comment by carllerche** [comment]
BytesMut should probably impl IntoBuf

**Comment by carllerche** [comment]
I believe that the answer is "yes", but that `BytesMut` needs to improve. #158 represents the requested improvement. I'm going to close this issue now. Thanks for the report.
