### ISSUE TITLE
Add a "Bytes" Codec Implementation

### ISSUE THREAD

**Issue by cramertj** [tokio-rs/tokio-io#75]
IIUC, `AsyncRead` and `AsyncWrite` pretty much rely on `framed` in order to be useful in futures-rs-style combinators. However, there's no provided implementation of `Encoder` and `Decoder`, so users always have to pull one in from another crate or write their own, even if they just want to read bytes directly from a stream. Consider exposing a `Bytes` codec similar to [the one that already exists in the tokio-core examples.](https://github.com/tokio-rs/tokio-core/blob/85257e19af1a1fa0714a4c58297755f374cef949/examples/connect.rs#L133)

**Comment by alexcrichton** [comment]
Sounds plausible to me! I'd be fine vendoring a "lines" version as well
