### ISSUE TITLE
Decoder::decode is slow for large buffers

### ISSUE THREAD

**Issue by sudeep9** [tokio-rs/tokio-io#79]
I am new to async I/O, Rust & tokio. So forgive me if I diagnosed the problem incorrectly.
My frame contains of header & data. The header tells the length of the data. The data in my case tends to be large ... say 1MB+. 

As I understand `Decoder::decode` is supposed to return `None` when enough bytes are not present to complete the frame. The header gets parsed quickly for but large content which follows the header,  the decoder keeps on returning `None` for a long time and things slow down considerably.

Is there a way for decoder to give a hint to `FramedRead` to say how much data the decoder is expecting? If yes, then the `FramedRead` would read that much amount of bytes exactly and then call `Decoder::decode`

**Comment by sudeep9** [comment]
I was wondering to roll my own `FrameRead`.  I suppose `tokio_io::io::read_exact` should do the job since I know exactly how much to read. 

However, the implementation of `read_exact` calls `std::io::read` in a tight loop ([link](https://docs.rs/tokio-io/0.1.3/src/tokio_io/read_exact.rs.html#56-83))

Will this not block the event loop for other I/O (say writes)?

**Comment by alexcrichton** [comment]
The I/O there is nonblocking, so I don't think it'll block anything unless it's compute bound.

**Comment by sudeep9** [comment]
I ended up writing my own FramedReader. So closing the issue
