### ISSUE TITLE
Rename `AsyncWrite::shutdown`

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio-io#80]
Because this function is unrelated to TCP shutdown (and the `AsyncWrite::shutdown` impl for `TcpStream` does *not* call shutdown), the name of the function is very confusing.

A couple of options:

* `finalize`
* `prepare_for_close`
* `poll_close_ready`
* `start_close`

Related: #73.

**Comment by P-E-Meunier** [comment]
Cool. Why is shutdown for `TcpStream` not calling TCP shutdown?
Other than this, I'd vote for `poll_close` (why the `_ready`?). I find `start_close` confusing, given that one is expected to call it until it returns `Async::Ready`.

**Comment by carllerche** [comment]
@P-E-Meunier Because "AsyncWrite::shutdown" and TCP shutdown are two completely separate functions with different behaviors.

This is why `AsyncWrite::shutdown` needs to be renamed.

**Comment by carllerche** [comment]
The tokio-io crate has been moved into the [tokio](https://github.com/tokio-rs/tokio) git repo.

I created a new issue over there. See link above.
