### ISSUE TITLE
Clarify behaviour of flush on WouldBlock error

### ISSUE THREAD

**Issue by AljoschaMeyer** [tokio-rs/tokio-io#88]
Is an implementation of the AsyncWrite trait allowed to block on `flush`ing?

The first sentence of the [trait doc comment](https://docs.rs/tokio-io/0.1.4/tokio_io/trait.AsyncWrite.html) indicates that this should not be the case:

> This trait inherits from io::Write and indicates that an I/O object is nonblocking, meaning that it will return an error instead of blocking when bytes cannot currently be written, but hasn't closed.

But the remainder of the documentation only explicitely talks about how `write` should handle `WouldBlock` errors, not about `flush`.

cc https://github.com/facebookincubator/rust-partial-io/issues/17

**Comment by sid0** [comment]
As of the latest version of partial-io, we're now treating `WouldBlock` during `flush` the same as `WouldBlock` during `write` as far as notifying the current task goes.

**Comment by carllerche** [comment]
@sid0 This is correct (and should be documented). It is expected that both `write` and `flush` will used from the same task.
